### PR TITLE
Add binding for CpuProfiler::CollectSample

### PR DESCRIPTION
**Pull request by Widdershin**
This is useful for capturing stacks at specific points.

### CODE REVIEW

**Comment by Widdershin** [comment]
If you're happy with this I can add the same functionality to `next`

**Comment by hyj1991** [comment]
Thanks for this pr :)

It seems helpful to add js stack manually when needed, but `collectSample()` seems to only be added in the new v8 version, could you please add the conditions like :

> https://github.com/hyj1991/v8-profiler-node8/blob/master/src/cpu_profiler.cc#L12

to adapt these node versions which  < node-v10.x.

**Comment by Widdershin** [comment]
Good point @hyj1991, I've added a conditional and used the old style for Node 8 and 9, as the API changed for v10 onwards.

Also just wanted to say thanks for your excellent work on this project and `next`, I've been using it quite a bit for 10 months or so and not run into any bugs with this project.

**Review by hyj1991 — APPROVED** [review]
+1

**Comment by Widdershin** [comment]
I had a look at the build failure and it's a bit strange.

I tested the Node v7 failure locally and it works. It looks like CI is using a cached binary:
```
[v8-profiler-node8] Success: "/home/travis/build/hyj1991/v8-profiler-node8/build/profiler/v6.2.0/node-v51-linux-x64/profiler.node" is installed via remote
```
Might just need to clear the caches there.

I can't seem to build locally on any version lower than v7, I run into errors about missing includes (algorithm and utils).

**Comment by hyj1991** [comment]
> I had a look at the build failure and it's a bit strange.
> 
> I tested the Node v7 failure locally and it works. It looks like CI is using a cached binary:
> 
> ```
> [v8-profiler-node8] Success: "/home/travis/build/hyj1991/v8-profiler-node8/build/profiler/v6.2.0/node-v51-linux-x64/profiler.node" is installed via remote
> ```
> 
> Might just need to clear the caches there.
> 
> I can't seem to build locally on any version lower than v7, I run into errors about missing includes (algorithm and utils).

I'll release the new binary on the release page.

**Comment by Widdershin** [comment]
👍 thanks for the quick review and merge :)

I sorted out my build issues locally and can confirm it builds and tests on v5 and v6.

**Comment by Widdershin** [comment]
Thanks for the speedy release, updated and can confirm that the new functionality is working, at least on Node 10.

I also got a cached binary this time, when it had been manually building for earlier versions, so that's nice!

**Comment by hyj1991** [comment]
> Thanks for the speedy release, updated and can confirm that the new functionality is working, at least on Node 10.
> 
> I also got a cached binary this time, when it had been manually building for earlier versions, so that's nice!

I am glad that this project is helpful to you :)

**Pull request merged**
