### PR TITLE
test: add segfault-handler to test suite

### PR DESCRIPTION
**Pull request by Widdershin**

### CODE REVIEW

**Comment by hyj1991** [comment]
> image

Maybe this is an error which runtime itself (v14.x on windows)...

**Comment by hyj1991** [comment]
Ref: https://ci.appveyor.com/project/hyj1991/v8-profiler-node8/builds/33972016/job/fiifh0579ava0s3o

**Comment by Widdershin** [comment]
Yeah I was wondering the same thing, it's not like any of our code gets loaded as part of `npm install`.

**Comment by hyj1991** [comment]
But in the `v8-profiler-next`, I configured nightly build, and there isn't any error like this.

**Comment by hyj1991** [comment]
> But in the v8-profiler-next, I configured nightly build, and there isn't any error like this.

image

Ref: https://ci.appveyor.com/project/hyj1991/v8-profiler-next/history

**Comment by Widdershin** [comment]
Yeah I can't find any issues or PRs on the Node repo showing this as an issue, so it definitely seems like something strange. I just had a build get to the test step and exit without printing a segfault, so I'll see if it's making a crash.log.

Is there a build cache we could try clearing?

**Comment by hyj1991** [comment]
> Is there a build cache we could try clearing?

Seems that appveyor delivers a new VM to run ci every time, so there are no cached things.

**Comment by Widdershin** [comment]
The fact that it sometimes happens on `npm --version` really confuses me. Surely that's not loading our project?

**Comment by hyj1991** [comment]
I want to change the `appveyor.yml`: 

```yml
sudo: false
language: node_js
node_js:
  - "14"
script: npm run test
```

Only run v14.x

**Comment by hyj1991** [comment]
More importantly, this error occurred almost every time with node-v14x.

**Comment by hyj1991** [comment]
It looks like a bug of the runtime itself on `ia32` (default appveyor windows VM), but usually we use is `x64`, so I set the platform:

```yml
# use x86_64, default is ia32
platform:
  - x64

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version x64
```

**Comment by hyj1991** [comment]
#18

**Pull request closed without merging**
