### PR TITLE
deps: Add support for Node 15 and 16 (v7.x-staging)

### PR DESCRIPTION
**Pull request by Widdershin**
Sorry, put this work on the wrong branch, here it is for `v7.x-staging`.

Thanks as always :)

### CODE REVIEW

**Review by hyj1991 — APPROVED** [review]

**Comment by Widdershin** [comment]
Thanks. Would it be possible to release this in the near future? I'm happy to help out with releases if you'd like.

**Comment by hyj1991** [comment]
> Thanks. Would it be possible to release this in the near future? I'm happy to help out with releases if you'd like.

OK, and what is your npm user name? I will add you to the owner list so that you can also publish this package.

**Comment by Widdershin** [comment]
I'm `widdershin` on [npm](https://www.npmjs.com/~widdershin) as well. And thanks :)

**Comment by hyj1991** [comment]
> OK, and what is your npm user name? I will add you to the owner list so that you can also publish this package.

done :)

You can try to publish `v8-profiler-node8@next`.

**Comment by Widdershin** [comment]
Cool I'll give it a go :) just curious, how do you generate and publish the binaries? 😃 not sure which of the scripts to use.

**Comment by hyj1991** [comment]
> Cool I'll give it a go :) just curious, how do you generate and publish the binaries? 😃 not sure which of the scripts to use.

Local compile

**Comment by Widdershin** [comment]
I was working on using Github Actions for compilation anyway, have put up a PR for doing that with this project: https://github.com/hyj1991/v8-profiler-node8/pull/34

**Comment by Widdershin** [comment]
Forgot to say, released `v7.3.0@next`, binaries auto-generated after I pushed the tag and it seems like everything is working well :)

**Pull request merged**
