### PR TITLE
feat: compatible with 7.x@next

### PR DESCRIPTION
**Pull request by hyj1991**
@Widdershin Hi, could you help to test whether the `new_7.x` branch is fully compatible with your application?

If ok, I will release `v8-profiler-node8@v7.4.0` which is based on this branch, no longer needs to provide pre-compiled binaries, and is fully based on `v8-profiler-next`.

Reference: https://github.com/hyj1991/v8-profiler-node8/issues/39

### CODE REVIEW

**Comment by hyj1991** [comment]
Actually, I still use env `V8_PROFILER_EAGER_LOGGING` to decide which logging mode will be used and also only recreate the profiler after a thousand profiles have been captured:

```js
'use strict';

const profiler = require('v8-profiler-next');

const startProfiling = profiler.startProfiling;
profiler.startProfiling = function (name, recsamples, mode) {
  if ([0, 1].indexOf(mode) === -1) {
    mode = process.env.V8_PROFILER_EAGER_LOGGING ? 1 : 0;
  }
  startProfiling.call(profiler, name, recsamples, mode);
}

profiler.setProfilesCleanupLimit(1000);

module.exports = profiler;
```

**Comment by Widdershin** [comment]
Yup, I’ll do some testing and review early next week.

**Comment by hyj1991** [comment]
@Widdershin Hi, I didn't mean to hurry, but has there been any progress on this pr :)

**Comment by Widdershin** [comment]
Sorry, not yet! Will try to get to it in the next few days :)

**Comment by Widdershin** [comment]
Just tried it out today, main issue I ran into was missing `collectSample` support. Are there any plans to support that in `next`?

Aside from that it works well.

Still need to do some performance/memory testing :)

**Comment by hyj1991** [comment]
> Just tried it out today, main issue I ran into was missing collectSample support. Are there any plans to support that in next?

~~Is there an example to show that? I'll support it in `v8-profiler-next`.~~

**Comment by hyj1991** [comment]
@Widdershin See https://github.com/hyj1991/v8-profiler-next/pull/51, will be landed in `v8-profiler-next@1.9.0`.

**Pull request merged**
