### PR TITLE
Port profiler memory leak to 7.x

### PR DESCRIPTION
**Pull request by hyj1991**
Reference: https://github.com/hyj1991/v8-profiler-next/issues/28

### CODE REVIEW

**Comment by Widdershin** [comment]
Will review, benchmark and test on Monday :)

**Comment by Widdershin** [comment]
Nice, verified this fixes the memory leak, and seems to work well with my project.

Screen Shot 2021-06-28 at 17 22 43

Great work 👍

**Comment by hyj1991** [comment]
I'll publish it after ci passing :)

**Comment by Widdershin** [comment]
@hyj1991 can you hold up on releasing momentarily? I just ran into a performance issue, will have a patch soon

**Comment by Widdershin** [comment]
If you're running one profile at a time, recreating the profiler each time can be very slow (up to 15x slower when benchmarking empty profiles one after the other). Seems to work better if we only recreate every so often.

**Comment by hyj1991** [comment]
> If you're running one profile at a time, recreating the profiler each time can be very slow (up to 15x slower when benchmarking empty profiles one after the other). Seems to work better if we only recreate every so often.

👌

**Pull request merged**
